### ISSUE TITLE
VSCode does not detect vite-imagetools parameters

### ISSUE THREAD

**Issue by khromov** [JonasKruckenberg/imagetools#566] opened 2023-05-28 17:46 UTC
I have a SvelteKit project where I have added vite-imagetools like this in `vite.config.ts`:

```ts
import { sveltekit } from '@sveltejs/kit/vite';
import type { UserConfig } from 'vite';
import { imagetools } from 'vite-imagetools';

const config: UserConfig = {
	plugins: [
		imagetools(),
		sveltekit(),
	]
};

export default config;
```

Building the project works correctly, but VS Code complains as soon as I add a query param:

![Screenshot 2023-05-28 at 19 45 10](https://github.com/JonasKruckenberg/imagetools/assets/1207507/9940bf6c-2335-4e6b-9750-668569dba915)

The same issue shows if I add `?format=webp` and also if I use direct paths (without $lib alias)

Is there some way to add the annotations to VS Code?

**Comment by michaelmichael** [comment] 2023-08-16 19:34
There are several strategies in #160 that should help you.

**Comment by khromov** [comment] 2023-08-16 19:36
Thanks! I saw that there is also https://github.com/JonasKruckenberg/imagetools/issues/532 on the same topic!

**Comment by JonasKruckenberg** [comment] 2023-09-09 22:45
closing as duplicate of #160

**Closed by JonasKruckenberg** 2023-09-09 22:45 UTC
