### ISSUE TITLE
How to import dynamic paths with Vite's `new URL(url, import.meta.url)`?

### ISSUE THREAD

**Issue by imShara** [JonasKruckenberg/imagetools#327] opened 2022-04-27 01:32 UTC
Hello. I'm trying to use it with latest Vite with this construction:

```js
const image = new URL(`/data/articles/${id}/picture.jpg?width=100`, import.meta.url).href
...
<img :src="image">
```

[More about this construction](https://vitejs.dev/guide/assets.html#new-url-url-import-meta-url)

![image](https://user-images.githubusercontent.com/4913196/165420286-2077335a-85d0-4435-8c54-a0ddd95a268f.png)

But image variable is `undefined`. What I miss? Should it works? Possible simmilar to https://github.com/JonasKruckenberg/imagetools/issues/321

**Comment by RodrigoSosa96** [comment] 2022-07-11 21:14
I am having the same problem, I have my imgs in a json to import them dynamically.

if there is no solution for this, there is no way to import a folder of pictures and transform them?

**Comment by MoogyG** [comment] 2022-07-23 16:15
same here

**Comment by benmccann** [comment] 2022-12-18 04:37
Is this still occurring? I wonder if it was fixed by https://github.com/JonasKruckenberg/imagetools/pull/412

**Comment by holtergram** [comment] 2023-03-17 12:42
Same 😔
Does anyone have a workaround for this?

**Comment by chojnicki** [comment] 2023-03-24 10:29
@JonasKruckenberg could you maybe look at this? Would be great, because it's pretty important feature in Vite right now.


This works, and is also transformed by imagetools:
`const demo = (x) => new URL(`/src/assets/images/demo/${x}.jpg`, import.meta.url).href`

This does not:
`const demo = (x) => new URL(`/src/assets/images/demo/${x}.jpg?w=100`, import.meta.url).href`

**Comment by benmccann** [comment] 2023-04-26 18:06
@chojnicki could you provide a repository that reproduces your issue? I'm having a hard time telling from the code sample exactly how you might be using `vite-imagetools` as there is no `import` in your example

**Comment by benmccann** [comment] 2023-04-26 19:39
I don't quite understand why it's being attempted to do the following in this issue description:
```
const image = new URL(`/data/articles/${id}/picture.jpg?width=100`, import.meta.url).href
```

Can't you just do this instead?
```
await import(./data/articles/${id}/picture.jpg?width=100)
```

**Comment by benmccann** [comment] 2023-04-26 19:43
> I am having the same problem, I have my imgs in a json to import them dynamically.

Please note from the Vite docs that "the URL string must be static so it can be analyzed"

> if there is no solution for this, there is no way to import a folder of pictures and transform them?

You can import a folder of pictures and transform them with `import.meta.glob`. I just added it to the docs and example

**Comment by benmccann** [comment] 2023-04-26 21:01
@chojnicki this is a bug in Vite. I can reproduce this without `imagetools` being involved. I filed an issue here: https://github.com/vitejs/vite/issues/13017

**Comment by benmccann** [comment] 2023-04-27 03:56
I wanted to mention that I haven't found much of a use case for this feature yet.

To use an example, let's assume you've got something like in the issue description:
```
const image = new URL(`/data/articles/${id}/picture.jpg?width=100`, import.meta.url).href
```

You could also accomplish that by simply doing a relative import from the article page. You can also use `import.meta.glob` to build a list of all the matching images which you dynamically select from. I think if you really really needed to dynamically select just a single image and could afford to build a list of all the images you could probably do something like `import.meta.glob` in an API endpoint (`+server.js` for SvelteKit users) so that you only hold the list on the server.

If the article and image are coming from a dynamic source like a CMS then you're probably not going to be using `new URL(url, import.meta.url)` anyway.

I'd love to know if there's some use case that I'm overlooking.

**Comment by dbergey** [comment] 2023-04-27 19:34
I have a use-case for this: I'm porting a custom webpack loader we use for localization to be a Vite plugin. I'd like to be able to pass parameters to the loader at import() call-time. Here's how we do it in Webpack:

```
import(`custom-loader?{param1: 'a', param2: 'b'}!./locale/${locale}/strings.txt`
```

And here's how I'd do it using the proposed vite plugin:

```
// in vite.config.js
plugins: [customLoader({ include: /strings\.txt$/)]

// in my app
import(`./locale/${locale}/strings.txt?param1=a&param2=b`);
```

Which would work, but for the limitation on query strings in dynamic imports with variables. (I did try variations on `import.meta.glob` but that doesn't allow variables at all.)

**Comment by benmccann** [comment] 2023-05-04 19:30
The fix for this will be in the next version of Vite: https://github.com/vitejs/vite/pull/13034

**Comment by chojnicki** [comment] 2023-05-05 10:37
@benmccann Thanks for handling vite issue so well. Will check that when new vite stable version will be released.

About use case - it's very simple. I was using `import.meta.glob` for a long time, but is has one important "issue". It will not give you file names, but full paths to files as keys. Because of this, it harder to use such file in for example loops or any other scenario where file name comes from variable. Let's say I have photos of all flags (they should be svg's, but whatever), and want to display flag corresponding to user country. `:src="flags[user.country]"` - should be simple, but it's not. To do that you need to map that object first, and make keys as flag names. Easy, few lines of code, but it's boilerplate you need to use in every place you need that, which is pain in the ass. You cannot easily extract that `import.meta.glob` logic elsewhere, because glob path of course cannot be variable.

**Closed** 2023-10-18 16:03 UTC
