### ISSUE TITLE
An error occurred when the npm run build project was packaged, how should I solve it?

### ISSUE THREAD

**Issue by chinavane** [JonasKruckenberg/imagetools#515] opened 2023-03-07 12:55 UTC
![image](https://user-images.githubusercontent.com/8588836/223427845-afdd0a0b-8eaa-46b1-9e89-248e23779d01.png)

**Comment by cijiugechu** [comment] 2023-03-19 12:21
Try using the solutions in this [issue](https://github.com/JonasKruckenberg/imagetools/issues/160#issuecomment-965021959)

**Comment by benmccann** [comment] 2023-04-26 22:01
Closing as duplicate of https://github.com/JonasKruckenberg/imagetools/issues/532

**Closed** 2023-04-26 22:01 UTC
